AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'app/serializers/*'
   - 'app/channels/application_cable/*'
   - 'spec/spec_helper.rb'
   - 'db/seeds.rb'
   - 'db/migrate/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/CaseIndentation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
ClassLength:
  Max: 250
