# # Be sure to restart your server when you modify this file.

# # Your secret key is used for verifying the integrity of signed cookies.
# # If you change this key, all old signed cookies will become invalid!

# # Make sure the secret is at least 30 characters and all random,
# # no regular words or you'll be exposed to dictionary attacks.
# # You can use `rails secret` to generate a secure secret key.

# # Make sure the secrets in this file are kept private
# # if you're sharing your code publicly.

defaults: &defaults
  omniauth_provider_key: Settings.omniauth_provider_key
  omniauth_provider_secret: Settings.omniauth_provider_secret

development:
  <<: *defaults
  secret_key_base: Settings.secret_key_base

test:
  <<: *defaults
  secret_key_base: Settings.secret_key_base

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  secret_key_base: Settings.secret_key_base
